# Generated by Django 4.1.3 on 2023-01-04 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavorecidosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=150, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contrato', models.CharField(max_length=150)),
                ('num_sap', models.IntegerField()),
                ('id_coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_coordenador', to='app.favorecidosmodel')),
                ('id_proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_proponente', to='app.favorecidosmodel')),
            ],
        ),
    ]
