# Generated by Django 4.1.2 on 2023-01-25 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavorecidosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RubricaModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimentacaoModel',
            fields=[
                ('descricao', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contrato', models.CharField(max_length=150)),
                ('num_sap', models.IntegerField()),
                ('id_coordenador', models.ForeignKey(db_column='id_coordenador', on_delete=django.db.models.deletion.CASCADE, related_name='id_coordenador', to='app.favorecidosmodel')),
                ('id_proponente', models.ForeignKey(db_column='id_proponente', on_delete=django.db.models.deletion.CASCADE, related_name='id_proponente', to='app.favorecidosmodel')),
                ('id_usuario', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtratoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('observacao', models.CharField(blank=True, max_length=150)),
                ('id_favorecido', models.ForeignKey(db_column='id_favorecido', on_delete=django.db.models.deletion.CASCADE, related_name='id_favorecido', to='app.favorecidosmodel')),
                ('id_movimentacao', models.ForeignKey(db_column='id_movimentacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_movimentacao', to='app.tipomovimentacaomodel')),
                ('id_projeto', models.ForeignKey(db_column='id_projeto', on_delete=django.db.models.deletion.CASCADE, related_name='id_projeto', to='app.projetomodel')),
                ('id_rubrica', models.ForeignKey(db_column='id_rubrica', on_delete=django.db.models.deletion.CASCADE, related_name='id_rubrica', to='app.rubricamodel')),
                ('id_tag', models.ForeignKey(db_column='id_tag', on_delete=django.db.models.deletion.CASCADE, related_name='id_tag', to='app.tagmodel')),
            ],
        ),
    ]
