# Generated by Django 4.1.2 on 2023-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
