# Generated by Django 4.1.2 on 2023-01-17 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rubricamodel_tagmodel_tipomovimentacaomodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtratoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.CharField(max_length=150)),
                ('id_favorecido', models.ForeignKey(db_column='id_favorecido', on_delete=django.db.models.deletion.CASCADE, related_name='id_favorecido', to='app.favorecidosmodel')),
                ('id_movimentacao', models.ForeignKey(db_column='id_movimentacao', on_delete=django.db.models.deletion.CASCADE, related_name='id_movimentacao', to='app.tipomovimentacaomodel')),
                ('id_projeto', models.ForeignKey(db_column='id_projeto', on_delete=django.db.models.deletion.CASCADE, related_name='id_projeto', to='app.projetomodel')),
                ('id_rubrica', models.ForeignKey(db_column='id_rubrica', on_delete=django.db.models.deletion.CASCADE, related_name='id_rubrica', to='app.rubricamodel')),
                ('id_tag', models.ForeignKey(db_column='id_tag', on_delete=django.db.models.deletion.CASCADE, related_name='id_tag', to='app.tagmodel')),
            ],
        ),
    ]
