# Generated by Django 4.1.3 on 2023-01-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_favorecidosmodel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetomodel',
            name='id_coordenador',
            field=models.ForeignKey(db_column='id_coordenador', on_delete=django.db.models.deletion.CASCADE, related_name='id_coordenador', to='app.favorecidosmodel'),
        ),
        migrations.AlterField(
            model_name='projetomodel',
            name='id_proponente',
            field=models.ForeignKey(db_column='id_proponente', on_delete=django.db.models.deletion.CASCADE, related_name='id_proponente', to='app.favorecidosmodel'),
        ),
    ]
