# Generated by Django 4.1.2 on 2023-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rubricamodel_tagmodel_tipomovimentacaomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubricamodel',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
