# Generated by Django 4.1.2 on 2023-01-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rubricamodel_tagmodel_tipomovimentacaomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomodel',
            name='observacao',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
