# Generated by Django 4.1.2 on 2023-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_extratomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extratomodel',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
