# Generated by Django 4.1.3 on 2023-01-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrica', models.CharField(max_length=100)),
                ('X', models.CharField(max_length=100)),
                ('I', models.CharField(max_length=100)),
                ('R', models.CharField(max_length=100)),
                ('data_pg', models.DateField()),
                ('ch', models.CharField(max_length=100)),
                ('data_recibo', models.DateField()),
                ('recibo', models.IntegerField()),
                ('comp', models.DateField()),
                ('N', models.IntegerField()),
                ('pessoal', models.CharField(max_length=150)),
                ('favorecido_fornecedor', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=150)),
                ('credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
