# Generated by Django 4.1.2 on 2022-12-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanilhaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=5, max_digits=5)),
                ('telefone', models.CharField(max_length=100)),
                ('quantidade_dias_trabalhados', models.IntegerField()),
                ('salario_total', models.DecimalField(decimal_places=5, max_digits=5)),
            ],
        ),
    ]
