# Generated by Django 4.1.2 on 2022-12-23 10:02

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customusermodel_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='login',
            field=models.CharField(max_length=100, unique=True, validators=[account.models.username_validator]),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(max_length=100, validators=[account.models.password_validator]),
        ),
    ]
