# Generated by Django 4.1.3 on 2022-12-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
    ]
