# Generated by Django 4.1.2 on 2022-12-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customusermodel_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='login',
            new_name='username',
        ),
    ]
