# Generated by Django 4.1.3 on 2022-12-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_admin_customuser_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email',
            new_name='username',
        ),
    ]
