# Generated by Django 4.1.3 on 2022-12-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_email_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.EmailField(max_length=255, unique=True, verbose_name='username'),
        ),
    ]
