# Generated by Django 4.1.2 on 2022-12-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_username_customusermodel_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='login',
            new_name='username',
        ),
    ]
